# Form implementation generated from reading ui file '/Users/juliusarolovitch/Desktop/Pitt_Challenge2/med_input_gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 294)
        Form.setStyleSheet("background-color: rgb(255, 216, 89)")
        self.med_input_header = QtWidgets.QLabel(Form)
        self.med_input_header.setGeometry(QtCore.QRect(150, 20, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.med_input_header.setFont(font)
        self.med_input_header.setObjectName("med_input_header")
        self.med_input_subheader = QtWidgets.QLabel(Form)
        self.med_input_subheader.setGeometry(QtCore.QRect(100, 40, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.med_input_subheader.setFont(font)
        self.med_input_subheader.setObjectName("med_input_subheader")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 80, 381, 201))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.error_label = QtWidgets.QLabel(self.groupBox)
        self.error_label.setGeometry(QtCore.QRect(10, 10, 361, 16))
        self.error_label.setObjectName("error_label")
        self.med_text_input = QtWidgets.QPlainTextEdit(self.groupBox)
        self.med_text_input.setGeometry(QtCore.QRect(10, 60, 361, 31))
        self.med_text_input.setStyleSheet("background-color: white; color: black; border: 1px solid black;")
        self.med_text_input.setObjectName("med_text_input")
        self.med_input_send = QtWidgets.QPushButton(self.groupBox)
        self.med_input_send.setGeometry(QtCore.QRect(130, 160, 113, 32))
        self.med_input_send.setStyleSheet("background-color: rgb(255, 174, 0); border: 1px solid black; border-radius: 5px;")
        self.med_input_send.setObjectName("med_input_send")
        self.error_label_2 = QtWidgets.QLabel(self.groupBox)
        self.error_label_2.setGeometry(QtCore.QRect(10, 30, 361, 16))
        self.error_label_2.setObjectName("error_label_2")
        self.med_dosage_input = QtWidgets.QComboBox(self.groupBox)
        self.med_dosage_input.setGeometry(QtCore.QRect(10, 120, 171, 26))
        self.med_dosage_input.setStyleSheet("background-color: white; border: 1px solid black; color: black;")
        self.med_dosage_input.setObjectName("med_dosage_input")
        self.med_freq_input = QtWidgets.QComboBox(self.groupBox)
        self.med_freq_input.setGeometry(QtCore.QRect(200, 120, 171, 26))
        self.med_freq_input.setStyleSheet("background-color: white; border: 1px solid black; color: black;")
        self.med_freq_input.setObjectName("med_freq_input")
        self.med_dosage_label = QtWidgets.QLabel(self.groupBox)
        self.med_dosage_label.setGeometry(QtCore.QRect(10, 100, 161, 16))
        self.med_dosage_label.setObjectName("med_dosage_label")
        self.med_freq_label = QtWidgets.QLabel(self.groupBox)
        self.med_freq_label.setGeometry(QtCore.QRect(200, 100, 161, 16))
        self.med_freq_label.setObjectName("med_freq_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.med_input_header.setText(_translate("Form", "AccessRx"))
        self.med_input_subheader.setText(_translate("Form", "Prototype Gui For Pitt Challenge 2022"))
        self.error_label.setText(_translate("Form", "We weren\'t able to find your medication from the image."))
        self.med_text_input.setPlainText(_translate("Form", "Medication Name"))
        self.med_input_send.setText(_translate("Form", "Done!"))
        self.error_label_2.setText(_translate("Form", "Please input the information : "))
        self.med_dosage_label.setText(_translate("Form", "Medication dosage : "))
        self.med_freq_label.setText(_translate("Form", "Medication frequency : "))
